apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  namespace: qdrant
data:
  qdrant.yaml: |
    service:
      enable_auth: true
    consensus:
      enabled: true
      tick_period_ms: 100

